# Generated by Django 5.0.6 on 2025-07-06 06:01

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_buttons',
            field=wagtail.fields.StreamField([('button', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='If linking off-site, fill this and leave \'link\' blank.', required=False))], icon='link'))], blank=True, use_json_field=True),
        ),
    ] 