name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fayette_gop
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint & type-check
        run: |
          pip install black flake8 isort mypy
          black --check .
          isort --check-only .
          flake8 .
          mypy home fayette_gop

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/fayette_gop
        run: |
          pip install pytest
          pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install deps & lint
        working-directory: frontend
        run: |
          pnpm install
          pnpm exec eslint . --ext .ts,.tsx
          pnpm run build